import type { Metadata } from 'next';
import Link from 'next/link';
import styles from '../presentaciones/page.module.css';
import process from './proceso.module.css';

export const metadata: Metadata = {
  title: 'Cómo contratar | Código Nexo',
  description: 'Conoce qué recibirás, quién responde y cómo confirmamos tu pedido antes de cualquier pago.',
};
const whatsapp = 'https://wa.me/525529058845?text=Hola%2C%20quiero%20una%20cotizaci%C3%B3n%20con%20alcance%2C%20precio%20total%20y%20fecha%20de%20entrega.';
export default function Page() {
  return <main className={`${styles.page} ${process.page}`}>
    <section className={styles.hero}>
      <div><p className={styles.eyebrow}>CLARIDAD ANTES DE CONTRATAR</p><h1>Tu pedido por escrito.<br /><em>Una persona que responde.</em></h1><p className={styles.intro}>Primero entendemos lo que necesitas. Después recibes una propuesta con entregables, precio total y fecha. Consultar no genera ningún cobro.</p><a className={styles.primary} href={whatsapp}>Solicitar cotización por WhatsApp</a><p className={styles.trustLine}>Sin datos bancarios públicos · Sin cargos por consultar</p></div>
      <aside className={styles.offer}><p>QUIÉN ATIENDE TU PEDIDO</p><h2>Código Nexo</h2><p>Responsable del servicio: Ricardo García Zapata.</p><p>Conserva la cotización y el folio de tu pedido para solicitar avances, ajustes o aclaraciones.</p><a className={styles.emailTop} href="mailto:codigonexo.rgz@gmail.com">codigonexo.rgz@gmail.com</a><a className={styles.emailTop} href={whatsapp}>WhatsApp: +52 55 2905 8845</a></aside>
    </section>
    <section className={styles.sample}><p className={styles.eyebrow}>ENVÍA TU INFORMACIÓN</p><h2>Elige cómo compartir tu proyecto</h2><div className={styles.previewGrid}><article><h3>Por WhatsApp</h3><p>Cuéntanos qué necesitas y para cuándo. En la conversación puedes adjuntar documentos, imágenes o una muestra de tu archivo.</p><a className={styles.primary} href={whatsapp}>Escribir y adjuntar por WhatsApp</a></article><article><h3>Por correo</h3><p>Envía tus instrucciones y adjunta el archivo desde tu aplicación de correo. Si compartes un enlace privado, habilita acceso solo para nuestro correo.</p><a className={styles.primary} href="mailto:codigonexo.rgz@gmail.com?subject=Solicitud%20de%20cotizaci%C3%B3n&body=Hola%2C%20necesito%3A%20%0AFecha%20deseada%3A%20%0AFormato%20de%20entrega%3A%20%0AAdjunto%20una%20muestra%20para%20revisar%20el%20alcance.">Preparar correo con instrucciones</a></article></div><p className={styles.trustLine}>Para cotizar basta una muestra. Oculta datos personales que no sean necesarios. Los archivos se envían en WhatsApp o correo; esta página no los recibe ni los almacena. Si el botón de correo no abre una aplicación, escribe a codigonexo.rgz@gmail.com.</p><Link className={styles.email} href="/trust/seguridad-compliance">Cómo tratamos tus archivos y solicitudes</Link></section>
    <section><p className={styles.eyebrow}>PASO A PASO</p><h2>Del primer mensaje a la entrega</h2><div className={styles.steps}>
      <article><span>01</span><h3>Cuéntanos qué necesitas</h3><p>Comparte el objetivo, una muestra sin datos confidenciales y tu fecha deseada. Confirmamos si podemos ayudarte.</p></article>
      <article><span>02</span><h3>Revisa y acepta la cotización</h3><p>Recibes folio, alcance, formatos, idioma, precio total, fecha, revisiones y condiciones de cancelación. Los extras requieren tu aprobación.</p></article>
      <article><span>03</span><h3>Confirma el pago y recibe</h3><p>Cuando el medio de pago esté confirmado, enviamos las instrucciones por privado. Verificamos el abono y confirmamos por escrito el inicio y la entrega.</p></article>
    </div></section>
    <section className={styles.sample}><p className={styles.eyebrow}>ASÍ SE VERÁ TU PROPUESTA</p><h2>Todo lo importante en un solo lugar</h2><div className={process.document}>
      <div className={process.documentHeader}><h3>Código Nexo · Cotización</h3><span>EJEMPLO · NO ES UNA ORDEN DE COBRO</span></div>
      <dl><dt>Folio</dt><dd>CN-EJEMPLO-001</dd><dt>Servicio</dt><dd>Presentación editable de 6 diapositivas</dd><dt>Incluye</dt><dd>Diseño a partir de hasta 800 palabras proporcionadas por el cliente, en español. Entrega en PowerPoint y PDF.</dd><dt>Precio total de ejemplo</dt><dd>$250 MXN. La cotización definitiva confirmará el tratamiento fiscal aplicable; no se añaden cargos sin aceptación.</dd><dt>Fecha de entrega</dt><dd>Se acuerda por escrito según el material y la disponibilidad, antes del pago.</dd><dt>Revisión</dt><dd>Una ronda de ajustes dentro del alcance, enviada en una sola lista dentro de los 7 días posteriores a la entrega.</dd><dt>No incluye</dt><dd>Investigación, traducción, redacción extensa ni diapositivas adicionales. Se cotizan por separado.</dd><dt>Pago</dt><dd>Importe, etapa y medio confirmados en la propuesta definitiva. Este ejemplo no permite realizar pagos.</dd></dl>
      <p className={process.acceptance}>Aceptación del pedido: “Acepto la cotización [folio y versión], el alcance, el total, la fecha y las condiciones adjuntas”.</p>
    </div></section>
    <section className={styles.faq}><p className={styles.eyebrow}>COMPROMISOS DEL SERVICIO</p><h2>Qué pasa si necesitas una solución</h2>
      <details open><summary>Si la entrega no cumple lo acordado</summary><p>Corregimos sin costo los errores respecto al alcance aceptado. Si no podemos cumplir, ofrecemos la devolución correspondiente al trabajo no realizado o no conforme. Esto no limita los derechos que legalmente te correspondan.</p></details>
      <details><summary>Si necesitas cancelar</summary><p>Antes de iniciar el trabajo, devolvemos el importe recibido por el servicio cancelado. Si ya comenzó, documentamos el avance y calculamos la devolución según las etapas y valores aceptados previamente, respetando los derechos aplicables. Confirmamos por escrito el importe, el medio y la fecha de devolución.</p></details>
      <details><summary>Si cambia la fecha o el alcance</summary><p>Te avisamos y acordamos por escrito cómo resolverlo. No sustituimos unilateralmente la fecha aceptada. Los contenidos o funciones adicionales necesitan una nueva aprobación de precio y plazo.</p></details>
      <details><summary>Cómo solicitar ajustes o una aclaración</summary><p>Escribe al correo o WhatsApp de Código Nexo con el folio y una descripción del problema. Las revisiones de preferencia se reciben en una lista dentro de los 7 días posteriores a la entrega; ese plazo no elimina los derechos por incumplimiento. Para sitios web y organizadores, se incluye corrección de fallos del alcance reportados dentro de 15 días de la entrega.</p></details>
      <details><summary>Cómo funciona la transferencia</summary><p>WhatsApp coordina el pedido; el pago se realiza desde la aplicación de tu banco. Solo después de aceptar la propuesta y confirmar la disponibilidad del cobro enviamos banco, titular, CLABE, importe y referencia por privado. El titular debe coincidir con el responsable informado. Nunca solicitamos NIP, CVV, contraseñas ni códigos de verificación.</p></details>
      <details><summary>Qué confirmación recibes</summary><p>Tras comprobar el abono, recibes folio, importe, fecha, saldo pendiente y fecha de entrega. La confirmación comercial no sustituye el CFDI que corresponda. Si contratas mediante Fiverr u otra plataforma, el pedido, pago y entrega se gestionan dentro de ella, conforme a sus condiciones.</p></details>
    </section>
    <section className={styles.closing}><h2>Empecemos por tu pendiente</h2><p>Revisamos tu caso y te enviamos una propuesta. No necesitas depositar para consultar.</p><a className={styles.primary} href={whatsapp}>Quiero una cotización</a><Link className={styles.email} href="/ayuda-digital">Ver servicios y precios</Link></section>
  </main>;
}
