import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../presentaciones/page.module.css';
export const metadata: Metadata = {title:'Document formatting, presentations and websites | Código Nexo',description:'Get your existing documents, slides and website content ready to use. Editable deliverables, clear scope and written support in English or Spanish.',alternates:{canonical:'/en',languages:{en:'/en',es:'/ayuda-digital'}}};
const email='mailto:codigonexo.rgz@gmail.com?subject=Project%20enquiry&body=Service%3A%20%0ALanguage%3A%20%0AFile%20type%20and%20size%3A%20%0AWhat%20needs%20to%20change%3A%20%0ADeadline%20and%20time%20zone%3A%20%0A';
const offers=[
 ['Document formatting','MXN 150','Up to 3 pages and 900 supplied words, including one supplied table or image. Consistent headings, margins, fonts and page numbering. Editable Word and PDF.','2 business days'],
 ['Presentation cleanup','MXN 250','Up to 6 slides and 800 supplied words. Clear structure, readable design and editable PowerPoint plus PDF. Translation and research are quoted separately.','3 business days'],
 ['One-page service website','MXN 1,200','Up to 5 sections and 8 supplied images, in one language. Mobile layout, contact links, source files and one deployment to agreed compatible hosting. No store, payments or admin panel. Domain and hosting cost extra, confirmed before you order.','5 business days']
];
export default function EnglishPage(){return <main lang="en" className={styles.page}>
<section className={styles.hero}><div><p className={styles.eyebrow}>DOCUMENTS · PRESENTATIONS · WEBSITES</p><h1>Your content.<br/><em>Clear and ready to use.</em></h1><p className={styles.intro}>A document that will not stay in place. Slides that are hard to read. A service that needs its first website. Send me what you have and tell me what needs to work.</p><p className={styles.use}>I’m Ricardo, founder of Código Nexo. I help individuals, students and small businesses finish practical digital tasks.</p><a href={email} className={styles.primary}>Tell me about your project ↗</a><a href="#samples" className={styles.emailTop}>See editable samples first</a><p className={styles.trustLine}>Written communication in English or Spanish · Clear scope before work begins</p><Link href="/ayuda-digital" className={styles.email}>Ver servicios en español</Link></div><aside className={styles.offer}><h2>What you receive</h2><ul><li>A written scope, total price and delivery date.</li><li>Files in the agreed editable formats.</li><li>One round of revisions within the agreed scope.</li><li>Instructions for opening or using your deliverables.</li></ul><p>We start from your own content. Send the file type, size, goal and deadline so I can confirm the right package.</p></aside></section>
<section id="samples" className={styles.sample}><p className={styles.eyebrow}>ORIGINAL DEMONSTRATIONS</p><h2>See the work before you order</h2><p>These fictional examples were created by Código Nexo to demonstrate the service. They are not client projects or testimonials.</p><div className={styles.audiences}>
<article><Image src="/muestras/english/document-after.png" alt="Formatted workshop document with clear headings and schedule" width={620} height={803} style={{width:"100%",height:"auto",marginBottom:16}}/><h3>A document that is easy to follow</h3><p>The same workshop content, with a clear heading structure and a readable schedule. Both files remain editable.</p><div className={styles.downloads}><a href="/muestras/english/document-before.docx">Before · Word</a><a href="/muestras/english/document-after.docx">After · Word</a><a href="/muestras/english/document-after.pdf">Preview · PDF</a></div></article>
<article><Image src="/muestras/english/presentation-after.png" alt="Redesigned English workshop presentation" width={640} height={360} style={{width:"100%",height:"auto",marginBottom:16}}/><h3>Slides with a clearer hierarchy</h3><p>Three pairs of slides show how existing content becomes easier to present. Text remains editable in PowerPoint.</p><div className={styles.downloads}><a href="/muestras/english/presentation-before-after.pptx">Download PowerPoint</a><a href="/muestras/english/presentation-preview.pdf">Preview · PDF</a></div></article>
<article><h3>A simple service website</h3><p>A fictional independent professional’s page with a responsive layout and a clear enquiry path. Contact actions are demonstrations.</p><div className={styles.downloads}><a href="/demos/service-page/index.html">Open website demo ↗</a></div></article></div></section>
<section><p className={styles.eyebrow}>SMALL PROJECTS WITH A DEFINED SCOPE</p><h2>Choose a starting point</h2><p>Direct-service prices are in Mexican pesos (MXN). These are not US dollar prices. If you need a different payment currency, we confirm the available method, currency and final amount in writing before payment.</p><div className={styles.audiences}>{offers.map(([name,price,scope,time])=><article key={name}><h3>{name}</h3><p><strong>{price}</strong></p><p>{scope}</p><p>Delivery: {time} after all materials and the project are confirmed.</p><a href={email}>Check my project ↗</a></article>)}</div><p>One language per deliverable. One revision round, sent as a single list within 7 days of delivery. Additional content, translation, specialist editing and new functions require a separate quote. Platform orders follow the scope and price shown on that platform.</p></section>
<section><h2>A small tool for everyday follow-up</h2><p>Try a local task organizer: add, edit and search tasks, change their status, and export or import a backup. It stores data in this browser only. The demonstration does not send your records to a server.</p><a className={styles.primary} href="/demos/organizer/index.html">Try the organizer demo ↗</a><p className={styles.use}>A custom version for one process starts with the defined MXN 1,800 package: up to 3 screens and 8 fields per record, for one user and device. Shared accounts, cloud storage and integrations require a separate proposal.</p></section>
<section className={styles.faq}><h2>How your order works</h2><details open><summary>1. Share the problem and a sample</summary><p>Send the file type, approximate length, required output, chosen language and deadline with your time zone. A small sample is enough for the first assessment.</p></details><details><summary>2. Review the written proposal</summary><p>We confirm what is included, the total price, delivery date, revision window and payment terms. An enquiry does not create a charge. Payment arrangements are confirmed before work begins. Orders placed on a marketplace stay on that platform.</p></details><details><summary>3. Receive usable files and request adjustments</summary><p>We check the agreed deliverables and provide opening or usage instructions. Send included adjustments in one list. New requirements are priced before additional work starts.</p></details><details><summary>Can you help with student work?</summary><p>Yes, with formatting, clarity and presentation of your own material, following your institution’s rules. You remain responsible for your ideas, sources and explanation of the work.</p></details><details><summary>What support comes with a website or organizer?</summary><p>Correction of faults within the agreed scope, reported within 15 days of delivery. Ongoing maintenance, new features, hosting and recurring services are agreed separately.</p></details></section>
<section className={styles.closing}><h2>What would you like to finish?</h2><p>Tell me what you already have and what you need next.</p><a className={styles.primary} href={email}>Open a project enquiry email ↗</a><a className={styles.email} href="https://wa.me/525529058845?text=Hello%2C%20I%20would%20like%20help%20with%20a%20digital%20project.">Prefer WhatsApp? Send a written message</a></section></main>}
